### ISSUE TITLE
cs.aim_lock_pi

### ISSUE THREAD

**Issue by Kurskikh** [Priler/csgobot#3]
Привет! не находит при запуске cs.aim_lock_pi. Можешь помочь найти, плиз? Если на бусти полная версия, я там подпишусь , заберу)

(venv) PS H:\csgobot> python.exe .\main.py
Traceback (most recent call last):
  File "H:\csgobot\main.py", line 18, in <module>
    from cs.aim_lock_pi import Locker
ModuleNotFoundError: No module named 'cs.aim_lock_pi'

**Comment by megatocha** [comment]
проблема всё ещё остаётся.
import cs просто не работает

```
No module named 'cs.aim_lock_pi'
  File "*******", line 18, in <module>
    from cs.aim_lock_pi import Locker
ModuleNotFoundError: No module named 'cs.aim_lock_pi'
```

**Comment by umkattown** [comment]
у него не хватает файлов он не все загрузил

**Comment by quvyster** [comment]
как я понял это скрипт для автонаводки. строчку с импортом этого файла можно просто скомментировать и будут просто отображатся квадратики. также нужно будет самому обучить нейронку (
